/*
 * generated by Xtext 2.26.0
 */
package xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtext.parser.antlr.internal.InternalCNNDescLangParser;
import xtext.services.CNNDescLangGrammarAccess;

public class CNNDescLangParser extends AbstractAntlrParser {

	@Inject
	private CNNDescLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCNNDescLangParser createParser(XtextTokenStream stream) {
		return new InternalCNNDescLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "CNNDescLang";
	}

	public CNNDescLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CNNDescLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
