/*
 * generated by Xtext 2.25.0
 */
package xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import stateMachineLanguage.ui.internal.StateMachineLanguageActivator;

public class SMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StateMachineLanguageActivator.getInstance().getInjector("xtext.SML");
	}

}
