/**
 * generated by Xtext 2.26.0
 */
package xtext.sML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Classification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.sML.Classification#getDrop <em>Drop</em>}</li>
 *   <li>{@link xtext.sML.Classification#getD <em>D</em>}</li>
 * </ul>
 *
 * @see xtext.sML.SMLPackage#getClassification()
 * @model
 * @generated
 */
public interface Classification extends EObject
{
  /**
   * Returns the value of the '<em><b>Drop</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Drop</em>' attribute.
   * @see #setDrop(String)
   * @see xtext.sML.SMLPackage#getClassification_Drop()
   * @model
   * @generated
   */
  String getDrop();

  /**
   * Sets the value of the '{@link xtext.sML.Classification#getDrop <em>Drop</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Drop</em>' attribute.
   * @see #getDrop()
   * @generated
   */
  void setDrop(String value);

  /**
   * Returns the value of the '<em><b>D</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>D</em>' attribute.
   * @see #setD(String)
   * @see xtext.sML.SMLPackage#getClassification_D()
   * @model
   * @generated
   */
  String getD();

  /**
   * Sets the value of the '{@link xtext.sML.Classification#getD <em>D</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>D</em>' attribute.
   * @see #getD()
   * @generated
   */
  void setD(String value);

} // Classification
