/**
 * generated by Xtext 2.25.0
 */
package xtext.sML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Highway</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.sML.Highway#getDb <em>Db</em>}</li>
 *   <li>{@link xtext.sML.Highway#getLeftNonRec <em>Left Non Rec</em>}</li>
 *   <li>{@link xtext.sML.Highway#getConv <em>Conv</em>}</li>
 *   <li>{@link xtext.sML.Highway#getFm <em>Fm</em>}</li>
 * </ul>
 *
 * @see xtext.sML.SMLPackage#getHighway()
 * @model
 * @generated
 */
public interface Highway extends EObject
{
  /**
   * Returns the value of the '<em><b>Db</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Db</em>' attribute list.
   * @see xtext.sML.SMLPackage#getHighway_Db()
   * @model unique="false"
   * @generated
   */
  EList<String> getDb();

  /**
   * Returns the value of the '<em><b>Left Non Rec</b></em>' containment reference list.
   * The list contents are of type {@link xtext.sML.LeftNonRecursive}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left Non Rec</em>' containment reference list.
   * @see xtext.sML.SMLPackage#getHighway_LeftNonRec()
   * @model containment="true"
   * @generated
   */
  EList<LeftNonRecursive> getLeftNonRec();

  /**
   * Returns the value of the '<em><b>Conv</b></em>' containment reference list.
   * The list contents are of type {@link xtext.sML.Convolution}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conv</em>' containment reference list.
   * @see xtext.sML.SMLPackage#getHighway_Conv()
   * @model containment="true"
   * @generated
   */
  EList<Convolution> getConv();

  /**
   * Returns the value of the '<em><b>Fm</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fm</em>' attribute list.
   * @see xtext.sML.SMLPackage#getHighway_Fm()
   * @model unique="false"
   * @generated
   */
  EList<String> getFm();

} // Highway
