/**
 * generated by Xtext 2.25.0
 */
package xtext.sML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Left Non Recursive</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.sML.LeftNonRecursive#getP <em>P</em>}</li>
 *   <li>{@link xtext.sML.LeftNonRecursive#getConvdrop <em>Convdrop</em>}</li>
 *   <li>{@link xtext.sML.LeftNonRecursive#getPool <em>Pool</em>}</li>
 * </ul>
 *
 * @see xtext.sML.SMLPackage#getLeftNonRecursive()
 * @model
 * @generated
 */
public interface LeftNonRecursive extends EObject
{
  /**
   * Returns the value of the '<em><b>P</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>P</em>' attribute.
   * @see #setP(String)
   * @see xtext.sML.SMLPackage#getLeftNonRecursive_P()
   * @model
   * @generated
   */
  String getP();

  /**
   * Sets the value of the '{@link xtext.sML.LeftNonRecursive#getP <em>P</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>P</em>' attribute.
   * @see #getP()
   * @generated
   */
  void setP(String value);

  /**
   * Returns the value of the '<em><b>Convdrop</b></em>' containment reference list.
   * The list contents are of type {@link xtext.sML.ConvDrop}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Convdrop</em>' containment reference list.
   * @see xtext.sML.SMLPackage#getLeftNonRecursive_Convdrop()
   * @model containment="true"
   * @generated
   */
  EList<ConvDrop> getConvdrop();

  /**
   * Returns the value of the '<em><b>Pool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pool</em>' attribute.
   * @see #setPool(String)
   * @see xtext.sML.SMLPackage#getLeftNonRecursive_Pool()
   * @model
   * @generated
   */
  String getPool();

  /**
   * Sets the value of the '{@link xtext.sML.LeftNonRecursive#getPool <em>Pool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pool</em>' attribute.
   * @see #getPool()
   * @generated
   */
  void setPool(String value);

} // LeftNonRecursive
