/**
 * generated by Xtext 2.25.0
 */
package xtext.sML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Left Recu</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.sML.LeftRecu#getP <em>P</em>}</li>
 *   <li>{@link xtext.sML.LeftRecu#getConvdropbegin <em>Convdropbegin</em>}</li>
 *   <li>{@link xtext.sML.LeftRecu#getMerge <em>Merge</em>}</li>
 *   <li>{@link xtext.sML.LeftRecu#getConvdropend <em>Convdropend</em>}</li>
 *   <li>{@link xtext.sML.LeftRecu#getPool <em>Pool</em>}</li>
 * </ul>
 *
 * @see xtext.sML.SMLPackage#getLeftRecu()
 * @model
 * @generated
 */
public interface LeftRecu extends EObject
{
  /**
   * Returns the value of the '<em><b>P</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>P</em>' attribute.
   * @see #setP(String)
   * @see xtext.sML.SMLPackage#getLeftRecu_P()
   * @model
   * @generated
   */
  String getP();

  /**
   * Sets the value of the '{@link xtext.sML.LeftRecu#getP <em>P</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>P</em>' attribute.
   * @see #getP()
   * @generated
   */
  void setP(String value);

  /**
   * Returns the value of the '<em><b>Convdropbegin</b></em>' containment reference list.
   * The list contents are of type {@link xtext.sML.ConvDrop}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Convdropbegin</em>' containment reference list.
   * @see xtext.sML.SMLPackage#getLeftRecu_Convdropbegin()
   * @model containment="true"
   * @generated
   */
  EList<ConvDrop> getConvdropbegin();

  /**
   * Returns the value of the '<em><b>Merge</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Merge</em>' containment reference.
   * @see #setMerge(Merge)
   * @see xtext.sML.SMLPackage#getLeftRecu_Merge()
   * @model containment="true"
   * @generated
   */
  Merge getMerge();

  /**
   * Sets the value of the '{@link xtext.sML.LeftRecu#getMerge <em>Merge</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Merge</em>' containment reference.
   * @see #getMerge()
   * @generated
   */
  void setMerge(Merge value);

  /**
   * Returns the value of the '<em><b>Convdropend</b></em>' containment reference list.
   * The list contents are of type {@link xtext.sML.ConvDrop}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Convdropend</em>' containment reference list.
   * @see xtext.sML.SMLPackage#getLeftRecu_Convdropend()
   * @model containment="true"
   * @generated
   */
  EList<ConvDrop> getConvdropend();

  /**
   * Returns the value of the '<em><b>Pool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pool</em>' attribute.
   * @see #setPool(String)
   * @see xtext.sML.SMLPackage#getLeftRecu_Pool()
   * @model
   * @generated
   */
  String getPool();

  /**
   * Sets the value of the '{@link xtext.sML.LeftRecu#getPool <em>Pool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pool</em>' attribute.
   * @see #getPool()
   * @generated
   */
  void setPool(String value);

} // LeftRecu
