/**
 * generated by Xtext 2.25.0
 */
package xtext.sML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Merge Non Recu</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.sML.MergeNonRecu#getDb <em>Db</em>}</li>
 *   <li>{@link xtext.sML.MergeNonRecu#getLeftNonRec <em>Left Non Rec</em>}</li>
 *   <li>{@link xtext.sML.MergeNonRecu#getVirg <em>Virg</em>}</li>
 *   <li>{@link xtext.sML.MergeNonRecu#getRight <em>Right</em>}</li>
 *   <li>{@link xtext.sML.MergeNonRecu#getFm <em>Fm</em>}</li>
 * </ul>
 *
 * @see xtext.sML.SMLPackage#getMergeNonRecu()
 * @model
 * @generated
 */
public interface MergeNonRecu extends EObject
{
  /**
   * Returns the value of the '<em><b>Db</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Db</em>' attribute.
   * @see #setDb(String)
   * @see xtext.sML.SMLPackage#getMergeNonRecu_Db()
   * @model
   * @generated
   */
  String getDb();

  /**
   * Sets the value of the '{@link xtext.sML.MergeNonRecu#getDb <em>Db</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Db</em>' attribute.
   * @see #getDb()
   * @generated
   */
  void setDb(String value);

  /**
   * Returns the value of the '<em><b>Left Non Rec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left Non Rec</em>' containment reference.
   * @see #setLeftNonRec(LeftNonRecursive)
   * @see xtext.sML.SMLPackage#getMergeNonRecu_LeftNonRec()
   * @model containment="true"
   * @generated
   */
  LeftNonRecursive getLeftNonRec();

  /**
   * Sets the value of the '{@link xtext.sML.MergeNonRecu#getLeftNonRec <em>Left Non Rec</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left Non Rec</em>' containment reference.
   * @see #getLeftNonRec()
   * @generated
   */
  void setLeftNonRec(LeftNonRecursive value);

  /**
   * Returns the value of the '<em><b>Virg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Virg</em>' attribute.
   * @see #setVirg(String)
   * @see xtext.sML.SMLPackage#getMergeNonRecu_Virg()
   * @model
   * @generated
   */
  String getVirg();

  /**
   * Sets the value of the '{@link xtext.sML.MergeNonRecu#getVirg <em>Virg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Virg</em>' attribute.
   * @see #getVirg()
   * @generated
   */
  void setVirg(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Right)
   * @see xtext.sML.SMLPackage#getMergeNonRecu_Right()
   * @model containment="true"
   * @generated
   */
  Right getRight();

  /**
   * Sets the value of the '{@link xtext.sML.MergeNonRecu#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Right value);

  /**
   * Returns the value of the '<em><b>Fm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fm</em>' attribute.
   * @see #setFm(String)
   * @see xtext.sML.SMLPackage#getMergeNonRecu_Fm()
   * @model
   * @generated
   */
  String getFm();

  /**
   * Sets the value of the '{@link xtext.sML.MergeNonRecu#getFm <em>Fm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fm</em>' attribute.
   * @see #getFm()
   * @generated
   */
  void setFm(String value);

} // MergeNonRecu
