/**
 * generated by Xtext 2.26.0
 */
package xtext.sML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Merge</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.sML.Merge#getDb <em>Db</em>}</li>
 *   <li>{@link xtext.sML.Merge#getMergeBody <em>Merge Body</em>}</li>
 *   <li>{@link xtext.sML.Merge#getFm <em>Fm</em>}</li>
 * </ul>
 *
 * @see xtext.sML.SMLPackage#getMerge()
 * @model
 * @generated
 */
public interface Merge extends EObject
{
  /**
   * Returns the value of the '<em><b>Db</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Db</em>' attribute.
   * @see #setDb(String)
   * @see xtext.sML.SMLPackage#getMerge_Db()
   * @model
   * @generated
   */
  String getDb();

  /**
   * Sets the value of the '{@link xtext.sML.Merge#getDb <em>Db</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Db</em>' attribute.
   * @see #getDb()
   * @generated
   */
  void setDb(String value);

  /**
   * Returns the value of the '<em><b>Merge Body</b></em>' containment reference list.
   * The list contents are of type {@link xtext.sML.MergeBody}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Merge Body</em>' containment reference list.
   * @see xtext.sML.SMLPackage#getMerge_MergeBody()
   * @model containment="true"
   * @generated
   */
  EList<MergeBody> getMergeBody();

  /**
   * Returns the value of the '<em><b>Fm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fm</em>' attribute.
   * @see #setFm(String)
   * @see xtext.sML.SMLPackage#getMerge_Fm()
   * @model
   * @generated
   */
  String getFm();

  /**
   * Sets the value of the '{@link xtext.sML.Merge#getFm <em>Fm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fm</em>' attribute.
   * @see #getFm()
   * @generated
   */
  void setFm(String value);

} // Merge
