/**
 * generated by Xtext 2.25.0
 */
package xtext.sML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Right</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.sML.Right#getConv <em>Conv</em>}</li>
 * </ul>
 *
 * @see xtext.sML.SMLPackage#getRight()
 * @model
 * @generated
 */
public interface Right extends EObject
{
  /**
   * Returns the value of the '<em><b>Conv</b></em>' containment reference list.
   * The list contents are of type {@link xtext.sML.Convolution}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conv</em>' containment reference list.
   * @see xtext.sML.SMLPackage#getRight_Conv()
   * @model containment="true"
   * @generated
   */
  EList<Convolution> getConv();

} // Right
