/**
 * generated by Xtext 2.26.0
 */
package xtext.cNNDescLang.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import xtext.cNNDescLang.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class CNNDescLangFactoryImpl extends EFactoryImpl implements CNNDescLangFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static CNNDescLangFactory init()
  {
    try
    {
      CNNDescLangFactory theCNNDescLangFactory = (CNNDescLangFactory)EPackage.Registry.INSTANCE.getEFactory(CNNDescLangPackage.eNS_URI);
      if (theCNNDescLangFactory != null)
      {
        return theCNNDescLangFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new CNNDescLangFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CNNDescLangFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case CNNDescLangPackage.CNN_DESC_LANG: return createCNNDescLang();
      case CNNDescLangPackage.ARCHITECTURE: return createArchitecture();
      case CNNDescLangPackage.CONVOLUTION: return createConvolution();
      case CNNDescLangPackage.FLATTEN_OR_GLOBAL: return createFlattenOrGlobal();
      case CNNDescLangPackage.INTERSTICE: return createInterstice();
      case CNNDescLangPackage.CLASSIFICATION: return createClassification();
      case CNNDescLangPackage.CONV_DROP: return createConvDrop();
      case CNNDescLangPackage.MERGE_CONV: return createMergeConv();
      case CNNDescLangPackage.CONV_OR_MERGE: return createConvOrMerge();
      case CNNDescLangPackage.LEFT: return createLeft();
      case CNNDescLangPackage.RIGHT: return createRight();
      case CNNDescLangPackage.MERGE_BODY: return createMergeBody();
      case CNNDescLangPackage.MERGE: return createMerge();
      case CNNDescLangPackage.FEATURE_EXTRACTION: return createFeatureExtraction();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CNNDescLang createCNNDescLang()
  {
    CNNDescLangImpl cnnDescLang = new CNNDescLangImpl();
    return cnnDescLang;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Architecture createArchitecture()
  {
    ArchitectureImpl architecture = new ArchitectureImpl();
    return architecture;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Convolution createConvolution()
  {
    ConvolutionImpl convolution = new ConvolutionImpl();
    return convolution;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FlattenOrGlobal createFlattenOrGlobal()
  {
    FlattenOrGlobalImpl flattenOrGlobal = new FlattenOrGlobalImpl();
    return flattenOrGlobal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Interstice createInterstice()
  {
    IntersticeImpl interstice = new IntersticeImpl();
    return interstice;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Classification createClassification()
  {
    ClassificationImpl classification = new ClassificationImpl();
    return classification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConvDrop createConvDrop()
  {
    ConvDropImpl convDrop = new ConvDropImpl();
    return convDrop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MergeConv createMergeConv()
  {
    MergeConvImpl mergeConv = new MergeConvImpl();
    return mergeConv;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConvOrMerge createConvOrMerge()
  {
    ConvOrMergeImpl convOrMerge = new ConvOrMergeImpl();
    return convOrMerge;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Left createLeft()
  {
    LeftImpl left = new LeftImpl();
    return left;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Right createRight()
  {
    RightImpl right = new RightImpl();
    return right;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MergeBody createMergeBody()
  {
    MergeBodyImpl mergeBody = new MergeBodyImpl();
    return mergeBody;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Merge createMerge()
  {
    MergeImpl merge = new MergeImpl();
    return merge;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FeatureExtraction createFeatureExtraction()
  {
    FeatureExtractionImpl featureExtraction = new FeatureExtractionImpl();
    return featureExtraction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CNNDescLangPackage getCNNDescLangPackage()
  {
    return (CNNDescLangPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static CNNDescLangPackage getPackage()
  {
    return CNNDescLangPackage.eINSTANCE;
  }

} //CNNDescLangFactoryImpl
