/**
 * generated by Xtext 2.26.0
 */
package xtext.cNNDescLang.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import xtext.cNNDescLang.CNNDescLangPackage;
import xtext.cNNDescLang.Merge;
import xtext.cNNDescLang.MergeBody;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Merge</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.cNNDescLang.impl.MergeImpl#getDb <em>Db</em>}</li>
 *   <li>{@link xtext.cNNDescLang.impl.MergeImpl#getMergeBody <em>Merge Body</em>}</li>
 *   <li>{@link xtext.cNNDescLang.impl.MergeImpl#getFm <em>Fm</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MergeImpl extends MinimalEObjectImpl.Container implements Merge
{
  /**
   * The default value of the '{@link #getDb() <em>Db</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDb()
   * @generated
   * @ordered
   */
  protected static final String DB_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDb() <em>Db</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDb()
   * @generated
   * @ordered
   */
  protected String db = DB_EDEFAULT;

  /**
   * The cached value of the '{@link #getMergeBody() <em>Merge Body</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMergeBody()
   * @generated
   * @ordered
   */
  protected EList<MergeBody> mergeBody;

  /**
   * The default value of the '{@link #getFm() <em>Fm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFm()
   * @generated
   * @ordered
   */
  protected static final String FM_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFm() <em>Fm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFm()
   * @generated
   * @ordered
   */
  protected String fm = FM_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MergeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CNNDescLangPackage.Literals.MERGE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDb()
  {
    return db;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDb(String newDb)
  {
    String oldDb = db;
    db = newDb;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CNNDescLangPackage.MERGE__DB, oldDb, db));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<MergeBody> getMergeBody()
  {
    if (mergeBody == null)
    {
      mergeBody = new EObjectContainmentEList<MergeBody>(MergeBody.class, this, CNNDescLangPackage.MERGE__MERGE_BODY);
    }
    return mergeBody;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFm()
  {
    return fm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFm(String newFm)
  {
    String oldFm = fm;
    fm = newFm;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CNNDescLangPackage.MERGE__FM, oldFm, fm));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CNNDescLangPackage.MERGE__MERGE_BODY:
        return ((InternalEList<?>)getMergeBody()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CNNDescLangPackage.MERGE__DB:
        return getDb();
      case CNNDescLangPackage.MERGE__MERGE_BODY:
        return getMergeBody();
      case CNNDescLangPackage.MERGE__FM:
        return getFm();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CNNDescLangPackage.MERGE__DB:
        setDb((String)newValue);
        return;
      case CNNDescLangPackage.MERGE__MERGE_BODY:
        getMergeBody().clear();
        getMergeBody().addAll((Collection<? extends MergeBody>)newValue);
        return;
      case CNNDescLangPackage.MERGE__FM:
        setFm((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CNNDescLangPackage.MERGE__DB:
        setDb(DB_EDEFAULT);
        return;
      case CNNDescLangPackage.MERGE__MERGE_BODY:
        getMergeBody().clear();
        return;
      case CNNDescLangPackage.MERGE__FM:
        setFm(FM_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CNNDescLangPackage.MERGE__DB:
        return DB_EDEFAULT == null ? db != null : !DB_EDEFAULT.equals(db);
      case CNNDescLangPackage.MERGE__MERGE_BODY:
        return mergeBody != null && !mergeBody.isEmpty();
      case CNNDescLangPackage.MERGE__FM:
        return FM_EDEFAULT == null ? fm != null : !FM_EDEFAULT.equals(fm);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (db: ");
    result.append(db);
    result.append(", fm: ");
    result.append(fm);
    result.append(')');
    return result.toString();
  }

} //MergeImpl
