/*
 * generated by Xtext 2.26.0
 */
package xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CNNDescLangStandaloneSetup extends CNNDescLangStandaloneSetupGenerated {

	public static void doSetup() {
		new CNNDescLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
