/*
 * generated by Xtext 2.26.0
 */
package xtext.ui.tests;

import cnngen.ui.internal.CnngenActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CNNDescLangUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CnngenActivator.getInstance().getInjector("xtext.CNNDescLang");
	}

}
