/**
 * generated by Xtext 2.25.0
 */
package xtext.sML.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import xtext.sML.Convolution;
import xtext.sML.FeatureExtraction;
import xtext.sML.Merge;
import xtext.sML.SMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Feature Extraction</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.sML.impl.FeatureExtractionImpl#getConv <em>Conv</em>}</li>
 *   <li>{@link xtext.sML.impl.FeatureExtractionImpl#getMerge <em>Merge</em>}</li>
 *   <li>{@link xtext.sML.impl.FeatureExtractionImpl#getDrop <em>Drop</em>}</li>
 *   <li>{@link xtext.sML.impl.FeatureExtractionImpl#getPool <em>Pool</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FeatureExtractionImpl extends MinimalEObjectImpl.Container implements FeatureExtraction
{
  /**
   * The cached value of the '{@link #getConv() <em>Conv</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConv()
   * @generated
   * @ordered
   */
  protected Convolution conv;

  /**
   * The cached value of the '{@link #getMerge() <em>Merge</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMerge()
   * @generated
   * @ordered
   */
  protected Merge merge;

  /**
   * The default value of the '{@link #getDrop() <em>Drop</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDrop()
   * @generated
   * @ordered
   */
  protected static final String DROP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDrop() <em>Drop</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDrop()
   * @generated
   * @ordered
   */
  protected String drop = DROP_EDEFAULT;

  /**
   * The default value of the '{@link #getPool() <em>Pool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPool()
   * @generated
   * @ordered
   */
  protected static final String POOL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPool() <em>Pool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPool()
   * @generated
   * @ordered
   */
  protected String pool = POOL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FeatureExtractionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SMLPackage.Literals.FEATURE_EXTRACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Convolution getConv()
  {
    return conv;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetConv(Convolution newConv, NotificationChain msgs)
  {
    Convolution oldConv = conv;
    conv = newConv;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SMLPackage.FEATURE_EXTRACTION__CONV, oldConv, newConv);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConv(Convolution newConv)
  {
    if (newConv != conv)
    {
      NotificationChain msgs = null;
      if (conv != null)
        msgs = ((InternalEObject)conv).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SMLPackage.FEATURE_EXTRACTION__CONV, null, msgs);
      if (newConv != null)
        msgs = ((InternalEObject)newConv).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SMLPackage.FEATURE_EXTRACTION__CONV, null, msgs);
      msgs = basicSetConv(newConv, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SMLPackage.FEATURE_EXTRACTION__CONV, newConv, newConv));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Merge getMerge()
  {
    return merge;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMerge(Merge newMerge, NotificationChain msgs)
  {
    Merge oldMerge = merge;
    merge = newMerge;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SMLPackage.FEATURE_EXTRACTION__MERGE, oldMerge, newMerge);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMerge(Merge newMerge)
  {
    if (newMerge != merge)
    {
      NotificationChain msgs = null;
      if (merge != null)
        msgs = ((InternalEObject)merge).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SMLPackage.FEATURE_EXTRACTION__MERGE, null, msgs);
      if (newMerge != null)
        msgs = ((InternalEObject)newMerge).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SMLPackage.FEATURE_EXTRACTION__MERGE, null, msgs);
      msgs = basicSetMerge(newMerge, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SMLPackage.FEATURE_EXTRACTION__MERGE, newMerge, newMerge));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDrop()
  {
    return drop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDrop(String newDrop)
  {
    String oldDrop = drop;
    drop = newDrop;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SMLPackage.FEATURE_EXTRACTION__DROP, oldDrop, drop));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPool()
  {
    return pool;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPool(String newPool)
  {
    String oldPool = pool;
    pool = newPool;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SMLPackage.FEATURE_EXTRACTION__POOL, oldPool, pool));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SMLPackage.FEATURE_EXTRACTION__CONV:
        return basicSetConv(null, msgs);
      case SMLPackage.FEATURE_EXTRACTION__MERGE:
        return basicSetMerge(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SMLPackage.FEATURE_EXTRACTION__CONV:
        return getConv();
      case SMLPackage.FEATURE_EXTRACTION__MERGE:
        return getMerge();
      case SMLPackage.FEATURE_EXTRACTION__DROP:
        return getDrop();
      case SMLPackage.FEATURE_EXTRACTION__POOL:
        return getPool();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SMLPackage.FEATURE_EXTRACTION__CONV:
        setConv((Convolution)newValue);
        return;
      case SMLPackage.FEATURE_EXTRACTION__MERGE:
        setMerge((Merge)newValue);
        return;
      case SMLPackage.FEATURE_EXTRACTION__DROP:
        setDrop((String)newValue);
        return;
      case SMLPackage.FEATURE_EXTRACTION__POOL:
        setPool((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SMLPackage.FEATURE_EXTRACTION__CONV:
        setConv((Convolution)null);
        return;
      case SMLPackage.FEATURE_EXTRACTION__MERGE:
        setMerge((Merge)null);
        return;
      case SMLPackage.FEATURE_EXTRACTION__DROP:
        setDrop(DROP_EDEFAULT);
        return;
      case SMLPackage.FEATURE_EXTRACTION__POOL:
        setPool(POOL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SMLPackage.FEATURE_EXTRACTION__CONV:
        return conv != null;
      case SMLPackage.FEATURE_EXTRACTION__MERGE:
        return merge != null;
      case SMLPackage.FEATURE_EXTRACTION__DROP:
        return DROP_EDEFAULT == null ? drop != null : !DROP_EDEFAULT.equals(drop);
      case SMLPackage.FEATURE_EXTRACTION__POOL:
        return POOL_EDEFAULT == null ? pool != null : !POOL_EDEFAULT.equals(pool);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (drop: ");
    result.append(drop);
    result.append(", pool: ");
    result.append(pool);
    result.append(')');
    return result.toString();
  }

} //FeatureExtractionImpl
