/**
 * generated by Xtext 2.25.0
 */
package xtext.sML.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import xtext.sML.ConvDrop;
import xtext.sML.LeftRecu;
import xtext.sML.Merge;
import xtext.sML.SMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Left Recu</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.sML.impl.LeftRecuImpl#getP <em>P</em>}</li>
 *   <li>{@link xtext.sML.impl.LeftRecuImpl#getConvdropbegin <em>Convdropbegin</em>}</li>
 *   <li>{@link xtext.sML.impl.LeftRecuImpl#getMerge <em>Merge</em>}</li>
 *   <li>{@link xtext.sML.impl.LeftRecuImpl#getConvdropend <em>Convdropend</em>}</li>
 *   <li>{@link xtext.sML.impl.LeftRecuImpl#getPool <em>Pool</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LeftRecuImpl extends MinimalEObjectImpl.Container implements LeftRecu
{
  /**
   * The default value of the '{@link #getP() <em>P</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getP()
   * @generated
   * @ordered
   */
  protected static final String P_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getP() <em>P</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getP()
   * @generated
   * @ordered
   */
  protected String p = P_EDEFAULT;

  /**
   * The cached value of the '{@link #getConvdropbegin() <em>Convdropbegin</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConvdropbegin()
   * @generated
   * @ordered
   */
  protected EList<ConvDrop> convdropbegin;

  /**
   * The cached value of the '{@link #getMerge() <em>Merge</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMerge()
   * @generated
   * @ordered
   */
  protected Merge merge;

  /**
   * The cached value of the '{@link #getConvdropend() <em>Convdropend</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConvdropend()
   * @generated
   * @ordered
   */
  protected EList<ConvDrop> convdropend;

  /**
   * The default value of the '{@link #getPool() <em>Pool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPool()
   * @generated
   * @ordered
   */
  protected static final String POOL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPool() <em>Pool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPool()
   * @generated
   * @ordered
   */
  protected String pool = POOL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LeftRecuImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SMLPackage.Literals.LEFT_RECU;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getP()
  {
    return p;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setP(String newP)
  {
    String oldP = p;
    p = newP;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SMLPackage.LEFT_RECU__P, oldP, p));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ConvDrop> getConvdropbegin()
  {
    if (convdropbegin == null)
    {
      convdropbegin = new EObjectContainmentEList<ConvDrop>(ConvDrop.class, this, SMLPackage.LEFT_RECU__CONVDROPBEGIN);
    }
    return convdropbegin;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Merge getMerge()
  {
    return merge;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMerge(Merge newMerge, NotificationChain msgs)
  {
    Merge oldMerge = merge;
    merge = newMerge;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SMLPackage.LEFT_RECU__MERGE, oldMerge, newMerge);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMerge(Merge newMerge)
  {
    if (newMerge != merge)
    {
      NotificationChain msgs = null;
      if (merge != null)
        msgs = ((InternalEObject)merge).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SMLPackage.LEFT_RECU__MERGE, null, msgs);
      if (newMerge != null)
        msgs = ((InternalEObject)newMerge).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SMLPackage.LEFT_RECU__MERGE, null, msgs);
      msgs = basicSetMerge(newMerge, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SMLPackage.LEFT_RECU__MERGE, newMerge, newMerge));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ConvDrop> getConvdropend()
  {
    if (convdropend == null)
    {
      convdropend = new EObjectContainmentEList<ConvDrop>(ConvDrop.class, this, SMLPackage.LEFT_RECU__CONVDROPEND);
    }
    return convdropend;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPool()
  {
    return pool;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPool(String newPool)
  {
    String oldPool = pool;
    pool = newPool;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SMLPackage.LEFT_RECU__POOL, oldPool, pool));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SMLPackage.LEFT_RECU__CONVDROPBEGIN:
        return ((InternalEList<?>)getConvdropbegin()).basicRemove(otherEnd, msgs);
      case SMLPackage.LEFT_RECU__MERGE:
        return basicSetMerge(null, msgs);
      case SMLPackage.LEFT_RECU__CONVDROPEND:
        return ((InternalEList<?>)getConvdropend()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SMLPackage.LEFT_RECU__P:
        return getP();
      case SMLPackage.LEFT_RECU__CONVDROPBEGIN:
        return getConvdropbegin();
      case SMLPackage.LEFT_RECU__MERGE:
        return getMerge();
      case SMLPackage.LEFT_RECU__CONVDROPEND:
        return getConvdropend();
      case SMLPackage.LEFT_RECU__POOL:
        return getPool();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SMLPackage.LEFT_RECU__P:
        setP((String)newValue);
        return;
      case SMLPackage.LEFT_RECU__CONVDROPBEGIN:
        getConvdropbegin().clear();
        getConvdropbegin().addAll((Collection<? extends ConvDrop>)newValue);
        return;
      case SMLPackage.LEFT_RECU__MERGE:
        setMerge((Merge)newValue);
        return;
      case SMLPackage.LEFT_RECU__CONVDROPEND:
        getConvdropend().clear();
        getConvdropend().addAll((Collection<? extends ConvDrop>)newValue);
        return;
      case SMLPackage.LEFT_RECU__POOL:
        setPool((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SMLPackage.LEFT_RECU__P:
        setP(P_EDEFAULT);
        return;
      case SMLPackage.LEFT_RECU__CONVDROPBEGIN:
        getConvdropbegin().clear();
        return;
      case SMLPackage.LEFT_RECU__MERGE:
        setMerge((Merge)null);
        return;
      case SMLPackage.LEFT_RECU__CONVDROPEND:
        getConvdropend().clear();
        return;
      case SMLPackage.LEFT_RECU__POOL:
        setPool(POOL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SMLPackage.LEFT_RECU__P:
        return P_EDEFAULT == null ? p != null : !P_EDEFAULT.equals(p);
      case SMLPackage.LEFT_RECU__CONVDROPBEGIN:
        return convdropbegin != null && !convdropbegin.isEmpty();
      case SMLPackage.LEFT_RECU__MERGE:
        return merge != null;
      case SMLPackage.LEFT_RECU__CONVDROPEND:
        return convdropend != null && !convdropend.isEmpty();
      case SMLPackage.LEFT_RECU__POOL:
        return POOL_EDEFAULT == null ? pool != null : !POOL_EDEFAULT.equals(pool);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (p: ");
    result.append(p);
    result.append(", pool: ");
    result.append(pool);
    result.append(')');
    return result.toString();
  }

} //LeftRecuImpl
