/*
 * generated by Xtext 2.26.0
 */
package xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CNNDescLangUiModule extends AbstractCNNDescLangUiModule {

	public CNNDescLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
