/*
 * generated by Xtext 2.26.0
 */
package xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCNNDescLangScopeProvider extends DelegatingScopeProvider {
}
