/**
 * generated by Xtext 2.26.0
 */
package xtext.cNNDescLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CNN Desc Lang</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.cNNDescLang.CNNDescLang#getCnndesclang <em>Cnndesclang</em>}</li>
 * </ul>
 *
 * @see xtext.cNNDescLang.CNNDescLangPackage#getCNNDescLang()
 * @model
 * @generated
 */
public interface CNNDescLang extends EObject
{
  /**
   * Returns the value of the '<em><b>Cnndesclang</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cnndesclang</em>' containment reference.
   * @see #setCnndesclang(Architecture)
   * @see xtext.cNNDescLang.CNNDescLangPackage#getCNNDescLang_Cnndesclang()
   * @model containment="true"
   * @generated
   */
  Architecture getCnndesclang();

  /**
   * Sets the value of the '{@link xtext.cNNDescLang.CNNDescLang#getCnndesclang <em>Cnndesclang</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cnndesclang</em>' containment reference.
   * @see #getCnndesclang()
   * @generated
   */
  void setCnndesclang(Architecture value);

} // CNNDescLang
