/**
 * generated by Xtext 2.26.0
 */
package xtext.cNNDescLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Flatten Or Global</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.cNNDescLang.FlattenOrGlobal#getFlat <em>Flat</em>}</li>
 *   <li>{@link xtext.cNNDescLang.FlattenOrGlobal#getGp <em>Gp</em>}</li>
 * </ul>
 *
 * @see xtext.cNNDescLang.CNNDescLangPackage#getFlattenOrGlobal()
 * @model
 * @generated
 */
public interface FlattenOrGlobal extends EObject
{
  /**
   * Returns the value of the '<em><b>Flat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Flat</em>' attribute.
   * @see #setFlat(String)
   * @see xtext.cNNDescLang.CNNDescLangPackage#getFlattenOrGlobal_Flat()
   * @model
   * @generated
   */
  String getFlat();

  /**
   * Sets the value of the '{@link xtext.cNNDescLang.FlattenOrGlobal#getFlat <em>Flat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Flat</em>' attribute.
   * @see #getFlat()
   * @generated
   */
  void setFlat(String value);

  /**
   * Returns the value of the '<em><b>Gp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gp</em>' attribute.
   * @see #setGp(String)
   * @see xtext.cNNDescLang.CNNDescLangPackage#getFlattenOrGlobal_Gp()
   * @model
   * @generated
   */
  String getGp();

  /**
   * Sets the value of the '{@link xtext.cNNDescLang.FlattenOrGlobal#getGp <em>Gp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gp</em>' attribute.
   * @see #getGp()
   * @generated
   */
  void setGp(String value);

} // FlattenOrGlobal
