/**
 * generated by Xtext 2.26.0
 */
package xtext.cNNDescLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Left</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.cNNDescLang.Left#getP <em>P</em>}</li>
 *   <li>{@link xtext.cNNDescLang.Left#getCom <em>Com</em>}</li>
 *   <li>{@link xtext.cNNDescLang.Left#getPool <em>Pool</em>}</li>
 * </ul>
 *
 * @see xtext.cNNDescLang.CNNDescLangPackage#getLeft()
 * @model
 * @generated
 */
public interface Left extends EObject
{
  /**
   * Returns the value of the '<em><b>P</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>P</em>' attribute.
   * @see #setP(String)
   * @see xtext.cNNDescLang.CNNDescLangPackage#getLeft_P()
   * @model
   * @generated
   */
  String getP();

  /**
   * Sets the value of the '{@link xtext.cNNDescLang.Left#getP <em>P</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>P</em>' attribute.
   * @see #getP()
   * @generated
   */
  void setP(String value);

  /**
   * Returns the value of the '<em><b>Com</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Com</em>' containment reference.
   * @see #setCom(ConvOrMerge)
   * @see xtext.cNNDescLang.CNNDescLangPackage#getLeft_Com()
   * @model containment="true"
   * @generated
   */
  ConvOrMerge getCom();

  /**
   * Sets the value of the '{@link xtext.cNNDescLang.Left#getCom <em>Com</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Com</em>' containment reference.
   * @see #getCom()
   * @generated
   */
  void setCom(ConvOrMerge value);

  /**
   * Returns the value of the '<em><b>Pool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pool</em>' attribute.
   * @see #setPool(String)
   * @see xtext.cNNDescLang.CNNDescLangPackage#getLeft_Pool()
   * @model
   * @generated
   */
  String getPool();

  /**
   * Sets the value of the '{@link xtext.cNNDescLang.Left#getPool <em>Pool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pool</em>' attribute.
   * @see #getPool()
   * @generated
   */
  void setPool(String value);

} // Left
