/**
 * generated by Xtext 2.26.0
 */
package xtext.cNNDescLang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Merge Conv</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.cNNDescLang.MergeConv#getMerge <em>Merge</em>}</li>
 *   <li>{@link xtext.cNNDescLang.MergeConv#getConvdrop <em>Convdrop</em>}</li>
 * </ul>
 *
 * @see xtext.cNNDescLang.CNNDescLangPackage#getMergeConv()
 * @model
 * @generated
 */
public interface MergeConv extends EObject
{
  /**
   * Returns the value of the '<em><b>Merge</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Merge</em>' containment reference.
   * @see #setMerge(Merge)
   * @see xtext.cNNDescLang.CNNDescLangPackage#getMergeConv_Merge()
   * @model containment="true"
   * @generated
   */
  Merge getMerge();

  /**
   * Sets the value of the '{@link xtext.cNNDescLang.MergeConv#getMerge <em>Merge</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Merge</em>' containment reference.
   * @see #getMerge()
   * @generated
   */
  void setMerge(Merge value);

  /**
   * Returns the value of the '<em><b>Convdrop</b></em>' containment reference list.
   * The list contents are of type {@link xtext.cNNDescLang.ConvDrop}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Convdrop</em>' containment reference list.
   * @see xtext.cNNDescLang.CNNDescLangPackage#getMergeConv_Convdrop()
   * @model containment="true"
   * @generated
   */
  EList<ConvDrop> getConvdrop();

} // MergeConv
